### ISSUE TITLE
Warning re. opendistro group

### ISSUE THREAD

**Issue by sjpb** [stackhpc/openhpc-demo#10]
```shell

$ ansible-playbook ansible/site.yml 

<snip>
PLAY [Validate kibana configuration] **************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: opendistro

PLAY [Validate opendistro configuration] *********************************

skipping: no hosts matched
```

Looks like the error is just the common groups missing an empty `opendistro` group? But not sure whether something else was supposed to happen here?

**Comment by sjpb** [comment]
Actually I think that probably the hosts for the validate opendistro task should be `elasticsearch` - @jovial is that right?

```ansible
- name: Validate opendistro configuration
  hosts: elasticsearch   # <-- currently opendistro
  tags: opendistro
  tasks:
    - import_role:
        name: opendistro
        tasks_from: validate.yml
      tags: validate
```

**Comment by jovial** [comment]
Think you are correct - being a bit inconsistent with the naming here. The convention is that the group should match the role, so I'm thinking we switch the group in common to `opendistro` or rename the role elasticsearch.

**Comment by sjpb** [comment]
I feel like actually "opendistro" itself is a poor project name as it's not very descriptive. However I think it makes sense to call the role "opendistro" so I'd be +1 for moving everything to that.

**Comment by jovial** [comment]
Agreed, which is why I originally went for elasticsearch. I will change the group to opendistro as you suggested.

**Comment by jovial** [comment]
Fixed with: https://github.com/stackhpc/openhpc-demo/commit/472c05bef613aa57a3e666293efc9cd75aa9511b
