### ISSUE TITLE
Need to document environment inventory

### ISSUE THREAD

**Issue by sjpb** [stackhpc/openhpc-demo#11]
We need to document what you have to/should define in `<env>/inventory`, otherwise you have to read all the role docs and figure out what common provides. I think it's something like:

1. A variable `openhpc_cluster_name=<cluster_name>` must be defined, e.g. in `<env>/inventory/group_vars/openhpc.yml`.
1. The `openhpc` role uses ansible groups of the form `<cluster_name>_<partition_name>`  to define Slurm partitions. The default partition name of "compute" is defined in `environments/common/inventory/group_vars/openhpc/defaults.yml`.
1. Hosts and groups can be defined in various ways but it is suggested that:
   - `environments/<env>/inventory/hosts` is produced by the deployment templating (e.g. from Terraform or Heat) and defines hosts directly in groups `<cluster_name>_compute` (if using default partition name) as well as `...login` and `...control`.
   - `environments/<env>/inventory/groups` is used to map these into the groups `{baremetal,vm}_{login,control,compute}`. These latter groups are what the playbooks use to set up hosts appropriately.
1. For more advanced options for Slurm partition definition see `https://github.com/stackhpc/ansible-role-openhpc#slurmconf`.

**Comment by sjpb** [comment]
@jovial interested to know if that looks right?

**Comment by sjpb** [comment]
Ah not quite right as `hosts` is after `groups` - so in 3. above the mapping to the baremetal/vm groups should also be done in `environments/<env>/inventory/hosts` - which keeps everything needing the cluster name in that file where it can be driven by templating, which is good.

**Comment by sjpb** [comment]
Actually the `openhpc_cluster_name` is probably then best defined in `<env>/inventory/hosts` as the name is probably templated from deployment code. Although this breaks the "role vars in group vars file of same name" pattern.

**Comment by jovial** [comment]
Awesome, thanks for putting this into words. 

> Actually the openhpc_cluster_name is probably then best defined in <env>/inventory/hosts as the name is probably templated from deployment code. Although this breaks the "role vars in group vars file of same name" pattern.

I think we should check that this variable is defined in validate.yml. I quite like the way it gets defined during infrastructure creation and passed through via the generated inventory. This avoids having to define it twice (and maintain alignment) or have a common configuration file that terraform and ansible both read.

Regarding the baremetal and vm distinction. I think we should remove the `baremetal_`, `vm` prefixed groups and instead define `baremetal` and `vm` groups. We could then use intersection groups to get  the equivalent of baremetal_compute, etc, eg: `baremetal&compute`. Although, as you brought up the other day, we aren't actually doing anything different for baremetal and visualised instances at the moment, so it probably makes sense to simplify the inventory and remove these until we have a need?

Did you want to make a commit adding this info or should I?

**Comment by sjpb** [comment]
I've got a bunch of commits in a private repo which also affect common/ so it can go in with those. Will discuss with you - it's based off the public multiple-environments branch so once that's merged into master we can start doing PRs to move stuff across.

**Comment by sjpb** [comment]
Note that ansible_user is now defined in `common/group_vars/all/defaults.yml`
