### ISSUE TITLE
Environment's inventory/hosts file is gitignored

### ISSUE THREAD

**Issue by sjpb** [stackhpc/openhpc-demo#12]
As defined by `environments/skeleton/{{cookiecutter.environment}}/.gitignore`

Is this what we want? I thought the one of the ideas here was to get inventories into the repo.

**Comment by jovial** [comment]
I don't think this will ignore the whole directory it just includes a standard blacklist per environment.

**Comment by sjpb** [comment]
Yep it just ignores the `hosts` file - but why do we want this?

**Comment by jovial** [comment]
Good point, I don't think this is desirable behaviour.

**Comment by jovial** [comment]
Fixed in: https://github.com/stackhpc/openhpc-demo/commit/2a963388e27952104254d7af0c92af7a7ccf23f9
