### ISSUE TITLE
Need to document groups

### ISSUE THREAD

**Issue by sjpb** [stackhpc/openhpc-demo#13]
Mostly clear to me but probably only cause of deploying monitoring, would be worth going thro the list (both master and both private versions)

**Comment by sjpb** [comment]
Also wonder if "implementation" groups like e.g. `podman` (are there any others) should be dynamically constructed. I.e. if a tool needs podman to run then it should add it's hosts to that group.

**Comment by jovial** [comment]
> Also wonder if "implementation" groups like e.g. podman (are there any others) should be dynamically constructed. I.e. if a tool needs podman to run then it should add it's hosts to that group.

Seems like a nice idea. Do you see any issues with doing something like
```
[podman:children]
opendistro
kibana
filebeat
```
?

> Mostly clear to me but probably only cause of deploying monitoring, would be worth going thro the list (both master and both private versions)

Are you thinking a table with all the groups that are available and a short summary of what they do?

**Comment by sjpb** [comment]
Ah, that's nice, LGTM.

Or maybe, we just add comments into `common/inventory/groups`? And point to it from the README(s)? Harder to get out of sync at least.

**Comment by sjpb** [comment]
Document that this ONLY supports:

1. Separate control and login nodes. The `login` group is passed as the `openhpc_login_only_nodes` to the openhpc role.
2. Configless mode.

This is intentional to cut down logic paths and make reasoning about groups etc simpler

**Comment by sjpb** [comment]
Should probably check that `cluster` and `openhpc` groups are used appropriately.

**Comment by sjpb** [comment]
Document something like:

- The hosts should be listed in a file `environments/<env>/inventory/hosts` which must define the following groups:
  - `control`: Containing a single host to make the Slurm control node. Multiple (high availability) control nodes are not supported.
  - `login`:  Containing one or more hosts to make Slurm login nodes. Note combined control/login nodes are not supported.
  - `compute`: Containing all hosts to become Slurm compute nodes (in all partitions).
  
  This file is usually created by the deployment automation.

- The cluster name must be defined for all hosts using `openhpc_cluster_name` - setting this in the hosts file using `[all:vars]` is usually convenient.
- Each Slurm partition must contain a homogeneous set of hosts. For each partition:
  - Define an ansible inventory group for each partition as `<cluster_name>_<partition_name>`.
  - Define the partition by setting `openhpc_slurm_partitions` in `environments/<env>/inventory/group_vars/openhpc/overrides.yml`.

  See the [openhpc role documentation](https://github.com/stackhpc/ansible-role-openhpc#slurmconf]) for more options.

**Comment by sjpb** [comment]
Document that we have "cluster" separate from "openhpc" so that the former can be a superset of the latter. Hence you need to specifically set the children of openhpc in the environment groups.

**Comment by sjpb** [comment]
Document the `environments/common/layouts` directory showing sensible `groups` defaults.

**Comment by sjpb** [comment]
Document `environments/common/inventory/group_vars/all/openhpc.yml: openhpc_packages` as being a place to add packages to be installed on all nodes?
