### ISSUE TITLE
[computes] is the only plural group

### ISSUE THREAD

**Issue by sjpb** [stackhpc/openhpc-demo#14]
Seems a bit inconsistent?

**Comment by jovial** [comment]
Yep, thought exactly the same myself and at least one user has accidentally used `--limit compute` and wondered why nothing was running! Lets change it before it is too late.

**Comment by jovial** [comment]
Fixed in https://github.com/stackhpc/openhpc-demo/commit/5ae58daa50db0497acd0b80808fd0dd31e1419d6#diff-d5f6d542a1922158d330812ff13c8f537dbc98647e25ad8d306ab9ace61cfb14
