### ISSUE TITLE
opendistro role not robust to node reboots

### ISSUE THREAD

**Issue by sjpb** [stackhpc/openhpc-demo#45]
Process:

1. Reimaged control node (running opendistro) with image based on CentOS 8.3 cloud image (had NIC drivers for baremetal added)
2. Ran ansible/site.yml. No issues
3. Rebooted control node
4. Ran ansible/site.yml again (with -v), failed with
```
RUNNING HANDLER [opendistro : Restart opendistro container] ************************************************************************
fatal: [control]: FAILED! => {
    "changed": true,
    "cmd": [
        "podman",
        "restart",
        "opendistro"
    ],
    "delta": "0:00:00.123763",
    "end": "2021-03-10 18:52:33.254267",
    "rc": 125,
    "start": "2021-03-10 18:52:33.130504"
}

STDERR:

time="2021-03-10T18:52:33Z" level=error msg="error joining network namespace for container 33f8339b621f796f39857ce66865980f08c7dc4280efa53d5ebc2e55118900b4: error retrieving network namespace at /tmp/podman-run-1001/netns/cni-fac24071-de13-0767-4afe-9f292689b129: unknown FS magic on \"/tmp/podman-run-1001/netns/cni-fac24071-de13-0767-4afe-9f292689b129\": ef53"
Error: container 33f8339b621f796f39857ce66865980f08c7dc4280efa53d5ebc2e55118900b4 conmon process missing, cannot retrieve exit code: conmon process killed
```
This error is in the `config` playbook of opendistro role.

5. Ran `ansible/site.yml` again, failed with:
```
TASK [opendistro : Setup opendistro] ***********************************************************************************************
fatal: [control]: FAILED! => {
    "changed": false
}

STDERR:

Error: unable to start container "33f8339b621f796f39857ce66865980f08c7dc4280efa53d5ebc2e55118900b4": unable to find user elasticsearch: no matching entries in passwd file



MSG:

Can't start container opendistro
```
which is in `deploy` playbook of role, i.e. later.
6. Ran `ansible/site.yml` again, same error as in 5.

**Comment by sjpb** [comment]
Just tried it again running monitoring.yml and it fails in the same deploy step but with a different message:
```
TASK [opendistro : Setup opendistro] **********************************************************************************************************************************************************************************
fatal: [nrel-control]: FAILED! => {
    "changed": false
}

STDERR:

Error: unable to start container "33f8339b621f796f39857ce66865980f08c7dc4280efa53d5ebc2e55118900b4": failed to mount shm tmpfs "/var/lib/podman/.local/share/containers/storage/overlay-containers/33f8339b621f796f39857ce66865980f08c7dc4280efa53d5ebc2e55118900b4/userdata/shm": invalid argument



MSG:

Can't start container opendistro
```

**Comment by oneswig** [comment]
Why is a network namespace required - perhaps default to host networking?

**Comment by sjpb** [comment]
Tried that on a new cluster. `site.yml` ran ok and monitoring worked. Then rebooted and reran `monitoring.yml` and get:
Reran site, now get:

```shell
TASK [opendistro : Setup opendistro] **********************************************************************************************************************************************************************************
fatal: [proto-control]: FAILED! => {
    "changed": false
}

STDERR:

Error: error freeing lock for container 675170ad19b1f3e07dc32ce074558fc2aad51fa9a75514868eca124711b1812b: no such file or directory

MSG:
Can't delete container opendistro
```

and podman shows:

```shell
[podman@proto-control ~]$ podman container ls
ERRO[0000] error joining network namespace for container 16346e2b93c4a644418a737896681466812823208184ac0294f4aed54571d86e: error retrieving network namespace at /tmp/podman-run-1001/netns/cni-128fd67c-2fde-21a7-3a87-120fffa602ad: unknown FS magic on "/tmp/podman-run-1001/netns/cni-128fd67c-2fde-21a7-3a87-120fffa602ad": ef53 
ERRO[0000] error joining network namespace for container 16911f2abb503df59bd992e7591be5e0377467cb62a8b3292cfe35b9ce6c9cec: error retrieving network namespace at /tmp/podman-run-1001/netns/cni-c9dfabfc-f33f-f041-422f-62cd83e101c4: unknown FS magic on "/tmp/podman-run-1001/netns/cni-c9dfabfc-f33f-f041-422f-62cd83e101c4": ef53 
Error: error joning network namespace of container 16346e2b93c4a644418a737896681466812823208184ac0294f4aed54571d86e: error retrieving network namespace at /tmp/podman-run-1001/netns/cni-128fd67c-2fde-21a7-3a87-120fffa602ad: unknown FS magic on "/tmp/podman-run-1001/netns/cni-128fd67c-2fde-21a7-3a87-120fffa602ad": ef53
```

which doesn't show that container at all.

**Comment by sjpb** [comment]
@jovial would be good to discuss container setup briefly so I know what's expected to exist/happen.

**Comment by jovial** [comment]
I've reproduced the issue and it seems to solved with:

```
sudo loginctl enable linger podman
```

before creating the containers.

Although things still aren't working quite as expected as the container isn't started automatically.
```
[podman@testohpc-control-0 ~]$ podman ps -a
CONTAINER ID  IMAGE                                                 COMMAND    CREATED        STATUS                         PORTS                   NAMES
22357ac87e68  docker.io/amazon/opendistro-for-elasticsearch:1.12.0  eswrapper  2 minutes ago  Exited (1) About a minute ago  0.0.0.0:9200->9200/tcp  opendistro
```

**Comment by sjpb** [comment]
Note this is probably not `opendistro` specific but applies to all containers!

**Comment by jovial** [comment]
So I realised we are missing the systemd unit files needed to start the containers on boot (and when they die). Here is what I think we need to do:

```
podman generate systemd opendistro --restart-policy always --name  > ~/.config/systemd/user/opendistro.service
```
The generated file does not work out of the box with customised ulimits, so we need to set these manually:

```
[podman@testohpc-control-0 ~]$ cat ~/.config/systemd/user/opendistro.service.d/limits.conf 
[Service]
# Systemd doesn't inherit values from /etc/security/limits.d
# https://bugzilla.redhat.com/show_bug.cgi?id=1364332
LimitNOFILE=65536
LimitMEMLOCK=infinity
```
For some reason these do not take effect unless you also change the cgroup-manager:

```
[podman@testohpc-control-0 ~]$ cat ~/.config/systemd/user/opendistro.service.d/overrides.conf 
[Service]
ExecStart=
# Workaround: Error: unable to start container
# "22357ac87e689814111f32d731c2446146b7f91cd9b02e644ed81130afd5e098":
# container_linux.go:370: starting container process caused:
# process_linux.go:459: container init caused: process_linux.go:382: setting
# rlimits for ready process caused: error setting rlimit type 6: operation not
# permitted: OCI permission denied
# NOTE: we have added the cgroup-manager=cgroupfs 
ExecStart=/usr/bin/podman start --cgroup-manager=cgroupfs opendistro
```
Without these modifications the error message will look like:

```
Error: unable to start container "22357ac87e689814111f32d731c2446146b7f91cd9b02e644ed81130afd5e098": container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: process_linux.go:382: setting rlimits for ready process caused: error setting rlimit type 6: operation not permitted: OCI permission denied
```

Note: that support for generating these files is not yet in the podman collection: https://github.com/containers/ansible-podman-collections/issues/18

We also need to switch to starting and stopping the containers with systemd and not `podman start` otherwise systemd will refuse to manage the service, here are the relevant lines from `journalctl --user -u opendistro`:

```
Mar 12 13:18:08 testohpc-control-0 systemd[1075]: opendistro.service: New main PID 33353 does not belong to service, and PID file is not owned by root. Refusing.
Mar 12 13:18:08 testohpc-control-0 systemd[1075]: opendistro.service: New main PID 33353 does not belong to service, and PID file is not owned by root. Refusing.
```

We should use the ansible equivalent of:

```
XDG_RUNTIME_DIR=/run/user/$UID systemctl --user restart opendistro
``

Note to get the user journal to work you need to use:

```
[Journal]
Storage=persistent
```
in `/etc/systemd/journald.conf` (we should probably do this by default).

**Comment by jovial** [comment]
> Tried that on a new cluster. `site.yml` ran ok and monitoring worked. Then rebooted and reran `monitoring.yml` and get:
> Reran site, now get:
> 
> ```shell
> TASK [opendistro : Setup opendistro] **********************************************************************************************************************************************************************************
> fatal: [proto-control]: FAILED! => {
>     "changed": false
> }
> 
> STDERR:
> 
> Error: error freeing lock for container 675170ad19b1f3e07dc32ce074558fc2aad51fa9a75514868eca124711b1812b: no such file or directory
> 
> MSG:
> Can't delete container opendistro
> ```
> 
> and podman shows:
> 
> ```shell
> [podman@proto-control ~]$ podman container ls
> ERRO[0000] error joining network namespace for container 16346e2b93c4a644418a737896681466812823208184ac0294f4aed54571d86e: error retrieving network namespace at /tmp/podman-run-1001/netns/cni-128fd67c-2fde-21a7-3a87-120fffa602ad: unknown FS magic on "/tmp/podman-run-1001/netns/cni-128fd67c-2fde-21a7-3a87-120fffa602ad": ef53 
> ERRO[0000] error joining network namespace for container 16911f2abb503df59bd992e7591be5e0377467cb62a8b3292cfe35b9ce6c9cec: error retrieving network namespace at /tmp/podman-run-1001/netns/cni-c9dfabfc-f33f-f041-422f-62cd83e101c4: unknown FS magic on "/tmp/podman-run-1001/netns/cni-c9dfabfc-f33f-f041-422f-62cd83e101c4": ef53 
> Error: error joning network namespace of container 16346e2b93c4a644418a737896681466812823208184ac0294f4aed54571d86e: error retrieving network namespace at /tmp/podman-run-1001/netns/cni-128fd67c-2fde-21a7-3a87-120fffa602ad: unknown FS magic on "/tmp/podman-run-1001/netns/cni-128fd67c-2fde-21a7-3a87-120fffa602ad": ef53
> ```
> 
> which doesn't show that container at all.

Just thought I'd note that you destroy all your state with:

```
sudo rm -rf ~podman/.local/share/containers/
```

You can probably do this in a less destructive way if you care about the data.

**Comment by jovial** [comment]
My analysis was incorrect before. I think I accidentally ran `podman start` instead of `systemctl start` and thought everything was rosy. I think the actual issue we are hitting is:

https://github.com/systemd/systemd/issues/13331

See also:

https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1837580

Where you can't raise `LimitMEMLOCK` beyond `64MB` when using `systemctl user`. I've come up with a new solution which is to use system level configuration i.e something like:

```
sudo -u podman sh -c 'podman generate systemd opendistro --restart-policy always --name' | sudo tee /etc/systemd/system/opendistro.service
```
Using the following overrides in `/etc/systemd/system/opendistro.service.d/overrides.conf`:

```
[Unit]
BindsTo=user@1001.service
After=user@1001.service

[Service]
User=podman
Group=podman
LimitNOFILE=65536
LimitMEMLOCK=infinity

```
 where `1001` is the uid of the podman user.

**Comment by sjpb** [comment]
I suspect we don't need the `--new` flag to `podman generate systemd`:
> The --new flag generates systemd unit files that create and remove containers at service start and stop commands (see ExecStartPre and ExecStopPost service actions)

We're using `containers.podman.podman_container` to create the container after all.

**Comment by jovial** [comment]
> I suspect we don't need the `--new` flag to `podman generate systemd`:
> 
> > The --new flag generates systemd unit files that create and remove containers at service start and stop commands (see ExecStartPre and ExecStopPost service actions)
> 
> We're using `containers.podman.podman_container` to create the container after all.

The idea was to switch to `podman run`,  and get rid of `containers.podman.podman_container` as per https://github.com/containers/podman/issues/5572#issuecomment-653574848. podman generate systemd --new` could be used to generate the basis of a template (would need tweaking) to ease the migration process.

**Comment by sjpb** [comment]
Without user lingering or BindsTo or After, hits this on reboot (this is run manually but rc matches what systemd reports):
```shell
Error: container 13fff305a82757d54303f4f627f9749c4e03edda29f91346b417ec90a5e191d7 and volume opendistro share lock ID 0: deadlock due to lock mismatch
[podman@proto-control ~]$ echo $?
126
```

**Comment by sjpb** [comment]
With user lingering and BindsTo/After, get this on first attempt to start in `journalctl`:

```
user@1001.service: Got notification message from PID 12523, but reception only permitted for main PID 11276
```

id is looked up from podman user in template and is correct.

**Comment by jovial** [comment]
> With user lingering and BindsTo/After, get this on first attempt to start in `journalctl`:
> 
> ```
> user@1001.service: Got notification message from PID 12523, but reception only permitted for main PID 11276
> ```
> 
> id is looked up from podman user in template and is correct.
> 
> This is the only useful info I've found so far: https://serverfault.com/a/835756/265372

By teh looks of things it looks like you might be using `NotifyAccess=main` (the default), have you tried with `NotifyAccess=all`?

**Comment by sjpb** [comment]
I'm using `NotifyAccess=all`.

**Comment by sjpb** [comment]
> Without user lingering or BindsTo or After, hits this on reboot (this is run manually but rc matches what systemd reports):
> 
> ```shell
> Error: container 13fff305a82757d54303f4f627f9749c4e03edda29f91346b417ec90a5e191d7 and volume opendistro share lock ID 0: deadlock due to lock mismatch
> [podman@proto-control ~]$ echo $?
> 126
> ```
> 
> have to delete the container and the volume before rerunning, will get complains about non-existent log file.
> 
> Suspect we're hitting this: [mheon/libpod@b8c9897](https://github.com/mheon/libpod/commit/b8c9897dcd54d321614d1d0f7b0f973547126660)

Now raised as a podman issue: https://github.com/containers/podman/issues/9765

Note that WITHOUT the user/group=podman it works ok (survives reboot) and this is the case even without the RuntimeDirectory directive (which was part of an earlier attempt to avoid pid issues when not using the --sdnotify=conman option)

**Comment by sjpb** [comment]
So `podman info --log-level=debug` shows:

`Using tmp dir /tmp/run-1001/libpod/tmp`

which is on `ext4` not a `tmpfs`. So according to https://github.com/containers/podman/issues/9765 the problem is that this directory isn't getting cleared up on reboot, hence podman doesn't detect the reboot and sort its state accordingly.

From podman docs:
> Distributions ship the /usr/share/containers/containers.conf file with their default settings. Administrators can override fields in this file by creating the /etc/containers/containers.conf

```
$ grep -i tmp /usr/share/containers/containers.conf
# Directory for temporary files. Must be tmpfs (wiped after reboot)
# tmp_dir = "/var/run/libpod
```

**Comment by sjpb** [comment]
Getting this info via ansible needs something horrible like:

```
- name: get tmp dir location
  command:
    cmd: podman info --log-level=debug
  register: podman_info

- debug:
    msg: "{{ podman_info.stderr_lines | regex_search('Using tmp dir (\\S+)', '\\1') }}"
```
which isn't quite right as it gives
```
['/run/user/1000/libpod/tmp"\',']
```

**Comment by sjpb** [comment]
Using `podman --tmpdir` doesn't appear to change the tmpdir used.
